name: Workflow for Simple Server
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile simple server
        run: make
      - name: Run server
        run: nohup ./server &
      - name: Run simple test
        run: |
          curl --http0.9 -v http://localhost:8000
          curl --http0.9 -v http://localhost:8000/test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: httpd.c main.c
