name: Workflow for Simple Server
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile simple server
        run: make
      - name: Run tests
        run: ./server
        run: curl http://localhost:8000
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          gcov: true
          gcov_include: httpd.c main.c
